### ISSUE TITLE
Required Features and Deficiencies

### ISSUE THREAD

**Issue by safak45x** [ryonakano/handy-football#5]
I will write here absolutely follow the necessary

**Comment by safak45x** [comment]
[İcon.zip](https://github.com/ryonakano/handy-football/files/5323221/Icon.zip)
concept app icon

**Comment by safak45x** [comment]
![2020-10-04 17-46-46 ekran görüntüsü](https://user-images.githubusercontent.com/59151376/95018910-1b0c7280-066b-11eb-9143-cd88d1889152.png)

**Comment by safak45x** [comment]
> [İcon.zip](https://github.com/ryonakano/handy-football/files/5323221/Icon.zip)
> concept app icon

![2020-10-04 17-58-31 ekran görüntüsü](https://user-images.githubusercontent.com/59151376/95018932-3b3c3180-066b-11eb-868e-a14e877953d3.png)
Practice this style when you score a goal

**Comment by safak45x** [comment]
Live score site
https://www.mackolik.com/canli-sonuclar
https://www.livescore.in/tr/
https://www.flashscore.com/
https://www.goal.com/tr/canl%C4%B1-skorlar
https://www.sporx.com/canliskorlar/#sportId=1
https://www.nesine.com/iddaa/canli-skor/futbol
https://www.ntvspor.net/canli-skorlar
https://www.fanatik.com.tr/canli-skor

**Comment by safak45x** [comment]
Add league and tournament
---Tournament--

UEFA Champions League
UEFA European league
Euro 2020
UEFA Nations League

--League---

Eredivisie
Ligue 1
Pro League

**Comment by safak45x** [comment]
> Live score site
> https://www.mackolik.com/canli-sonuclar
> https://www.livescore.in/tr/
> https://www.flashscore.com/
> https://www.goal.com/tr/canl%C4%B1-skorlar
> https://www.sporx.com/canliskorlar/#sportId=1
> https://www.nesine.com/iddaa/canli-skor/futbol
> https://www.ntvspor.net/canli-skorlar
> https://www.fanatik.com.tr/canli-skor

https://www.football-data.org/

**Comment by safak45x** [comment]
> > Live score site
> > https://www.mackolik.com/canli-sonuclar
> > https://www.livescore.in/tr/
> > https://www.flashscore.com/
> > https://www.goal.com/tr/canl%C4%B1-skorlar
> > https://www.sporx.com/canliskorlar/#sportId=1
> > https://www.nesine.com/iddaa/canli-skor/futbol
> > https://www.ntvspor.net/canli-skorlar
> > https://www.fanatik.com.tr/canli-skor
> 
> https://www.football-data.org/
> https://footballdatabase.com/scores

http://livescore.football-data.co.uk/
https://www.api-football.com/

**Comment by safak45x** [comment]
Let me know after the teams and live matches are added, I'll tell you what's and what's not.

**Comment by safak45x** [comment]
Positive negative write the improvements here I will help more

**Comment by safak45x** [comment]
![2020-10-05 19-10-24 ekran görüntüsü](https://user-images.githubusercontent.com/59151376/95106113-c2a7a480-0740-11eb-81ed-74fab959cc26.png)

**Comment by safak45x** [comment]
@ryonakano I wonder if you are reading what I wrote and my concept designs

**Comment by safak45x** [comment]
![2020-10-05 21-07-33 ekran görüntüsü](https://user-images.githubusercontent.com/59151376/95117344-16ba8500-0751-11eb-8a05-530f0173d3ee.png)

**Comment by ryonakano** [comment]
@safak45x Hi, sorry for my late reply and thank you for your ideas! Looks nice.

Would you make one Issue per one feature request / issue report so that I can keep track of each of them?
